"""Constants"""

# Aircraft Carrier - Portaaviones
AIRCRAFT_CARRIER_ID = "P"
DEFAULT_NUMBER_OF_AC = 1
DEFAULT_AC_LENGTH = 4

# Submarines - Submarinos
SUBMARINE_ID = "S"
DEFAULT_NUMBER_OF_SUB = 2
DEFAULT_SUB_LENGTH = 3

# Destroyer - Destructor
DESTROYER_ID = "D"
DEFAULT_NUMBER_OF_DES = 2
DEFAULT_DES_LENGTH = 2

# Frigate - Fragata
FRIGATE_ID = "F"
DEFAULT_NUMBER_OF_FRI = 2
DEFAULT_FRI_LENGTH = 1

DEFAULT_BOARDS_ROWS_NUM = 10
DEFAULT_BOARDS_COLUMNS_NUM = 10





